apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-swift-co-id
  namespace: default
spec:
  secretName: swift-wildcard-tls
  issuerRef:
    name: letsencrypt-dns         # <- match your ClusterIssuer name
    kind: ClusterIssuer
  dnsNames:
    - "*.swift.co.id"