apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflared
type: Opaque
stringData:
  token: eyJhIjoiY2MyYWRlZDExNTc2MGE4OTYyMzI4MmQ2ZGExNWQ3MGEiLCJ0IjoiNDIxNWFjZjYtZDE3MC00MjIzLWIyN2YtYTdhNmNjMzViOGNjIiwicyI6IlpqQmtZMkZtTlRjdE9EazBaaTAwWWpVMExXSTBZbVF0WkRoaU9ERmtZVFV3TnpGaSJ9

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: token
